---
title: "Sensory_permutation"
author: "May"
date: "1/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Cue disassociation test
# Gerry Carter

# load packages
library(tidyverse)
library(boot)
library(cowplot)
#library(lmer)
library(lmerTest)
library(purrr)
library(rstatix)
library(svglite)
library(beepr)

# pre-sets for saving plots (walk())
devices <- c('eps', 'pdf', 'jpeg', 'svg')


## plot palattes: 
loc <- "#c9caa8" #light green
odr<- "#f2cf43" #yellow
snd<- "#684e44" #brown purple
nthr<- "#cc935E" #terra cotta



# functions for bootstrapping 95% confidence intervals around the mean -----

# get mean and 95% CI of values x via bootstrapping
boot_ci <- function(x, perms=5000, bca=F) {
  get_mean <- function(x, d) {
    return(mean(x[d]))
  } 
  x <- as.vector(na.omit(x))
  mean <- mean(x)
  if(bca){
    boot <- boot.ci(boot(data=x, 
                         statistic=get_mean, 
                         R=perms, 
                         parallel = "multicore", 
                         ncpus = 4), 
                    type="bca")
    low <- boot$bca[1,4]
    high <- boot$bca[1,5] 
  }else{
    boot <- boot.ci(boot(data=x, 
                         statistic=get_mean, 
                         R=perms, 
                         parallel = "multicore", 
                         ncpus = 4), 
                    type="perc")
    low <- boot$perc[1,4]
    high <- boot$perc[1,5] 
  }
  c(low=low,mean=mean,high=high, N=round(length(x)))
}


# get mean and 95% CI via bootstrapping of values y within grouping variable x
boot_ci2 <- function(d=d, y=d$y, x=d$x, perms=5000, bca=F){
  df <- data.frame(effect=unique(x))
  df$low <- NA
  df$mean <- NA
  df$high <- NA
  df$n.obs <- NA
  for (i in 1:nrow(df)) {
    ys <- y[which(x==df$effect[i])] #pulls out all the e.g.location prefs
    if (length(ys)>1 & var(ys)>0 ){
      b <- boot_ci(y[which(x==df$effect[i])], perms=perms, bca=bca) #resamples with replacement the mean and ci for e.g. AJs pref for location, gives back the low mean and high
      df$low[i] <- b[1]
      df$mean[i] <- b[2]
      df$high[i] <- b[3]
      df$n.obs[i] <- b[4]
    }else{
      df$low[i] <- min(ys)
      df$mean[i] <- mean(ys)
      df$high[i] <- max(ys)
      df$n.obs[i] <- length(ys)
    }
  }
  df
}

# plot permutation test results

#one-tailed: 
# hist_perm_one <- function(exp=exp, obs=obs, perms=perms, label=''){
#   exp.range <- round(quantile(exp, probs= c(0.025, 0.975)),3)
#   ggplot()+
#     geom_histogram(aes(x=exp), color="black",fill="light blue")+
#     geom_vline(aes(xintercept=obs), color="red", size=1)+
#     xlab("expected values from null model")+
#     ggtitle( paste(names(obs)) , subtitle = paste('obs = ',round(obs,3), ', exp = ', exp.range[1], ' to ', exp.range[2], ", Prob exp >= obs: p", ifelse(mean(exp>=obs)==0,paste("<",1/perms), paste("=",signif(mean(exp>=obs),digits=2))),", permutations=",perms, sep=""))
# }


#two-tailed: Not 100 sure about this: Tried to center the values around 0 by subtracting the mean of the exp distribution from exp and obs, and then took the absolute value of the exp and subtract from absolute value of obs. (have to center bc mean of distribution is way different than 0 )
  
hist_perm <- function(exp=exp, obs=obs, perms=perms, label=''){
  exp.range <- round(quantile(exp, probs= c(0.025, 0.975)),3)
  ggplot()+
    geom_histogram(aes(x=exp), color="black",fill="light blue")+
    geom_vline(aes(xintercept=obs), color="red", size=1)+
    xlab("expected values from null model")+
    ggtitle( paste(names(obs)) , subtitle = paste('obs = ',round(obs,0), ', exp = ', round(exp.range[1],0), ' to ', round(exp.range[2],0), ", P", ifelse(mean(abs(exp-mean(exp))>=abs(obs-mean(exp)))==0,paste("<",1/perms), paste("=",signif(mean(abs(exp-mean(exp))>=abs(obs-mean(exp))),digits=2))), sep=""))
}



```

```{r load data}
# set directory
#setwd("~/Users/maydixon/GitHub/Sensory_learning/Sensory_learning_1")

# get data----

#all visits
d <- read.csv("https://raw.githubusercontent.com/maydixon/sensory_learning/master/Sensory_visits.csv", sep=",", header=TRUE, stringsAsFactors = F )%>% 
  rename(visits= visits_counts) %>% 
  mutate(Test= case_when(
    Test == "LocVSound" ~ "Location v Sound",
    Test == "LocVSmell" ~ "Location v Odor",
    Test == "SoundVSmell" ~ "Sound v Odor"))
 #on github
View(d)

#first visits
first_choices1 <- read.csv("https://raw.githubusercontent.com/maydixon/sensory_learning/master/first_choices.csv", sep=",", header=TRUE, stringsAsFactors = F )
View(first_choices1)
```


Probability of passing test by chance
```{r}
perms <- 50000
exp <-rep(NA, perms) 
for (i in 1:perms) {
  exp[i] <- sum(sample(c(F,F,F,T), 7, replace=T))
}
mean(exp>=5) 
xp <-rep(NA, 1000) 
for (i in 1:1000) {
  exp[i] <- sum(sample(c(F,F,F,T), 7, replace=T))
}
mean(exp>=5)
#Is that right??
  
```



```{r}
# plot AJ data by bat
d %>% 
  filter(Species=="AJ") %>% 
  ggplot(aes(x=cue, y=visits))+
    facet_grid(rows= vars(Bat.ID), cols= vars(Test), scales= "free")+
    geom_col(aes(fill=cue))

# plot L data by bat
d %>% 
  filter(Species=="L") %>% 
  ggplot(aes(x=cue, y=visits))+
  facet_grid(rows= vars(Bat.ID), cols= vars(Test), scales= "free")+
  geom_col(aes(fill=cue))
```

# what are the cue preferences by test?-----

# make function to plot data
```{r}
plot_preference <- function(species= "AJ", use_percent=T){
  
  # default method is to center visits by trial to remove effect of total number of choices
  # other method is to use proportions to remove effect of total number of choices
  if(use_percent){
    points <- 
      d %>% 
      # get species
      filter(Species==species) %>% 
      # center counts by bat
      group_by(Bat.ID, Test) %>% 
      mutate(pref = visits / sum(visits)) %>% 
      ungroup() %>% 
      # identify trial for bootstrapping
      mutate(effect= paste(cue, Test, sep="_"))  
 
  }else{
    points <- 
      d %>% 
      # get species
      filter(Species==species) %>% 
      # center counts by bat
      group_by(Bat.ID, Test) %>% 
      mutate(pref = visits - mean (visits)) %>% 
      ungroup() %>% 
      # identify trial for bootstrapping
      mutate(effect= paste(cue, Test, sep="_"))  
    
    
  }

      
      
      
  # get means and 95% CI
  set.seed(121)
  means <- 
    points %>% 
    boot_ci2(y=.$pref, x=.$effect) %>% 
    separate(effect, into=c('cue', 'Test'), sep="_", remove=F) 
  
  # plot means, 95% CI and raw data
  plot <- 
    means %>% 
    mutate(cue = fct_relevel(cue, 
            "location", "odor", "sound", "neither")) %>% #order the factor
    ggplot(aes(x=cue, y=mean, color=cue))+
    facet_wrap(~Test,  scales="free_x") + # the removing the strip currently doesn't work
    geom_point(size=3)+
    geom_jitter(data= points, aes(y= pref), size=1, alpha=0.5, width=0.1, height=0)+
    geom_errorbar(aes(ymin=low, ymax=high, width=.1), size=1)+
    geom_hline(yintercept = ifelse(use_percent, 0.33, 0), color= "dark grey")+
    ylab(ifelse(use_percent,
                "proportion of trial visits",
                "relative # visits (obs - exp)"))+
    xlab("Cues")+
    ggtitle(ifelse(species=="AJ", expression(paste("frugivorous ", italic("Artibeus jamaicensis"))), 
                                  expression(paste("predatory ", italic("Lophostoma silvicolum")))))+
    theme_cowplot()+
    theme(legend.position = "none") +
    # scale_color_manual(values=c('#1b9e77','dark grey','#d95f02','#7570b3'))
    
  # scale_color_manual(values=c('#c9cba3','#FFB833','#e26d5c','#723d46'))
  # list(means,plot)
    scale_color_manual(values=c(loc, odr, snd, nthr)) +
    
  scale_x_discrete(  labels=c("location" = "loc", "sound" = "sound", "smell" ="odor", "neither" = "neither"))
  
  list(means,plot) 
  
  
}

# get results----
# use that function to plot preferences for AJ
# table shows summary data that is plotted
(aj.results <- plot_preference(species="AJ", use_percent = F))

#export plot
 walk(devices, ~ ggsave(filename = paste("aj.results", .x), device = .x, units = "mm", width = 173, height = 100 ))

# use that function plot preferences for L
(l.results <- plot_preference(species="L", use_percent= F))
# export plot 
 walk(devices, ~ ggsave(filename = paste("l.results", .x), device = .x, units = "mm", width = 173, height = 100 ))
```

# Did bats have cue preferences on their first visits? 

#summarise first choices by Species, Test, add small value to 0 bars for plotting purposes only
```{r}
first_choices1 <- first_choices1[!is.na(first_choices1$first_visit), ] # remove empty rows / bats that never visited

first_visits_sum <- first_choices1 %>% 
  group_by(Species, Test, first_visit) %>% 
  summarise(n_visits= n()) %>% 
  rbind(data.frame(Species = c("AJ", "L"), Test = rep("LocVSmell",2), first_visit = rep("smell",2), n_visits = rep(0.2,2) )) %>%  #fill in missing 0 rows with small value for plotting (.3) 
  arrange(Species, Test)

first_visits_sum 
```

# plotting first visits faceted by test for each species

```{r}

# New facet label names for Test variable
Test.labs <- c("Location v Odor", "Location v Sound", "Sound v Odor")
names(Test.labs) <- c("LocVSmell", "LocVSound", "SovSm")



plot_FirstVisits <- function(species= "AJ"){

firstvisits <-
 first_visits_sum   %>% 
  mutate(first_visit = factor(first_visit, levels = c("location", "smell", "sound", "neither"))) %>% #reorder factor for plotting
  filter(Species == species) %>%
  ggplot(aes(x = first_visit, y = n_visits, fill = first_visit))+
  facet_wrap(~Test,  labeller = labeller(Test = Test.labs), scales="free_x")+ 
  geom_bar(stat = "identity")+
  ggtitle(ifelse(species=="AJ", expression(paste("frugivorous ", italic("Artibeus jamaicensis"))), expression(paste("predatory ", italic("Lophostoma silvicolum")))))+
  ylab("# Bats") +
  xlab("Cues") +
  scale_x_discrete(  labels=c("location" = "loc", "smell" ="odor", "sound" = "sound",  "neither" = "neither")) +
   scale_fill_manual(name = "First visit", values=c(loc, odr, snd, nthr)) +
   theme_cowplot() +
  theme(legend.position = "none")
list(firstvisits)
}

# plot AJ first visits
(aj.firstvisits<- plot_FirstVisits(species="AJ"))
# walk(devices, ~ ggsave(filename = paste("aj.firstvisits", .x), device = .x , units = "mm", width = 173, height = 60 ))

# plot Lophostoma first visits
(l.firstvisits<- plot_FirstVisits(species="L"))
# walk(devices, ~ ggsave(filename = paste("l.firstvisits", .x), device = .x , units = "mm", width = 173, height = 60 ))

```




# Are there species differences?-----
```{r}

# use permutation test to compare species (using null model that randomizes cue choices while controlling for everything else)


# get difference between species in mean number of visits to each cue
# store as vector of differences
## visit




obs <- 
  d %>% 
  mutate(cue = replace(cue, cue =="neither", "control")) %>% #trying to replace rename neither with control
  group_by(Species, cue, Test) %>% 
  summarize(visits= mean(visits)) %>% 
  pivot_wider(names_from = Species, values_from= visits) %>% 
  mutate(diff= AJ-L) %>% 
  arrange(Test,cue) %>% 
  mutate(effect= gsub(" ", " ", paste(Test, cue, sep=" - ")))  %>%  #identify trial, w removed spaces
  pull(diff,effect) #pull effect as "names" for obs



# numbers are AJ - L differences for:
# location, neither, odor, scent, for each test
# positive number means AJ made more visits
# we cannot interpret these without the null model of what to expect by chance!


obs
names(obs)
# get expected difference between species if bat choices of cue were random

# how many permutations?
perms <- 5000

# store results in matrix
exp <- matrix(NA, ncol=length(obs), nrow= perms) ##May: changed observed to obs
colnames(exp)<- names(obs) #name the columns for easier ID

# for loop to get expected results
for (i in 1:perms){
  
  exp[i,] <- 
    d %>% 
    # re-assign visits to different cues within each trial 
    group_by(Bat.ID, Test) %>% 
    mutate(visits = visits[sample(row_number())]) %>%  
    
    # get same number as before
    group_by(Species, cue, Test) %>% 
    summarize(visits= mean(visits), .groups= 'drop') %>% # May: what does drop do here? Gerry:just new version of tidyverse gives it a warning that says drop, so it doesn't give a random warning. 
    pivot_wider(names_from = Species, values_from= visits) %>% 
    mutate(diff= AJ-L) %>% 
    arrange(Test, cue) %>% 
    mutate(effect= paste(cue, Test, sep="_"))  %>%  #identify trial
    pull(diff,effect)
  beep(12)
}



H_names <- paste("hist", colnames(exp), sep = "_")

wd= 3
ht = 3
uts="in"
# Loc V Odor 
# get p-value for species difference for location (column 1)
(hist_LocationvOdor_control <- hist_perm(exp= exp[,1], obs= obs[1], perms=perms))
#ggsave(paste(paste("hist", names(obs[1]), ".png",sep = "_")), width = wd, units = uts, height = ht)

# get p-value for species difference for neither (column 2)
(hist_LocationvOdor_location <- hist_perm(exp= exp[,2], obs= obs[2], perms=perms))
#ggsave(paste(paste("hist", names(obs[2]), ".png",sep = "_")), width = wd, units = uts, height = ht)

# get p-value for species difference for odor (column 3)
(hist_LocationvOdor_odor <- hist_perm(exp= exp[,3], obs= obs[3], perms=perms))
#ggsave(paste(paste("hist", names(obs[3]), ".png",sep = "_")), width = wd, units = uts, height = ht)
# Loc v Sound

# get p-value for species difference for location (column 4)
(hist_LocationvSound_control<- hist_perm(exp= exp[,4], obs= obs[4], perms=perms)) #wrong
#ggsave(paste(paste("hist", names(obs[4]), ".png",sep = "_")), width = wd, units = uts, height = ht)

(hist_LocationvSound_location <- hist_perm(exp= exp[,5], obs= obs[5], perms=perms)) #wrong
#ggsave(paste(paste("hist", names(obs[5]), ".png",sep = "_")), width = wd, units = uts, height = ht)

(hist_LocationvSound_sound   <- hist_perm(exp= exp[,6], obs= obs[6], perms=perms))
#ggsave(paste(paste("hist", names(obs[6]), ".png",sep = "_")), width = wd, units = uts, height = ht)
  # Sound V Odor
  
(hist_SoundvOdor_control <- hist_perm(exp= exp[,7], obs= obs[7], perms=perms))
#ggsave(paste(paste("hist", names(obs[7]), ".png",sep = "_")), width = wd, units = uts, height = ht)

(hist_SoundvOdor_odor <- hist_perm(exp= exp[,8], obs= obs[8], perms=perms)  ) 
#ggsave(paste(paste("hist", names(obs[8]), ".png",sep = "_")), width = wd, units = uts, height = ht)

(hist_SoundvOdor_sound <- hist_perm(exp= exp[,9], obs= obs[9], perms=perms)
)
#ggsave(paste(paste("hist", names(obs[9]), ".png",sep = "_")), width = wd, units = uts, height = ht)



# make summary of species differences in relative # of visits to each cue
pct_difs <- d %>% 
   mutate(cue = replace(cue, cue =="neither", "control")) %>% #trying to replace rename neither with control
  group_by(Bat.ID, Test) %>%
  pivot_wider(names_from = cue, values_from = visits) %>%
  mutate(visits_trial = sum(c(location, sound, control, odor), na.rm = TRUE)) %>%#total visits in trial
  pivot_longer(cols = c(location, sound, control, odor), names_to = "cue", values_to = "visits", values_drop_na = TRUE) %>%
  mutate(prop_visit = visits/visits_trial*100) %>% ## shows the % of visits bat made to each cue type in a trial
  ungroup() %>%
  mutate(name= paste(cue, Test, sep="_"))  
  
sd_poold <- pct_difs %>%
  group_by(name) %>%
  summarize(sd_pool = sd(visits)) %>%
  ungroup()
 sd_poold  

pct_difs <- left_join(pct_difs, sd_poold)%>% ungroup()# add full pooled sds to data

#rm(sd_pool)

pct_difs <- pct_difs %>% 
  group_by(Species, cue, Test) %>% #get the average proportion of visits, and the spp difference in proportion visits
  
  summarize(mean_visits= mean(visits), sd = sd(visits), sd_pool = first(sd_pool), mean_prop = mean(prop_visit), n = n()) %>% 
  pivot_wider(names_from = Species, values_from= c(mean_visits, n, sd, sd_pool = sd_pool, mean_prop)) %>% 
  mutate(diff_visits = mean_visits_AJ - mean_visits_L, diff_prop= mean_prop_AJ - mean_prop_L) %>% 
  mutate(cohensd = (abs(diff_visits)) / (sqrt(((n_AJ - 1) *sd_AJ^2 + (n_L-1) * sd_L^2) / ((n_AJ - 1) + (n_L-1))))) %>%#cohens d calculation with sd calculated from each group seperately
mutate(cohensd2 = abs(diff_visits)/sd_pool_AJ) %>%
  mutate(name= paste(cue, Test, sep="_")) %>%
  
  arrange(Test,cue) %>% 
  relocate(c(Test, cue,diff_visits, diff_prop, mean_prop_AJ, mean_prop_L, cohensd,cohensd2, n_AJ, n_L))

pct_difs
# write.csv(pct_difs, "species_comparison_differences_propvisits.csv")

#two cohen's d methods produce slightly different results! what about with built in function? 

cohens3 <- d %>%
   mutate(cue = replace(cue, cue =="neither", "control")) %>%
  mutate(name= paste(cue, Test, sep="_"))  %>% 
  
  group_by(name) %>%
 cohens_d(visits ~ Species) %>% select(name, effsize)
  
compare_cohens <- left_join(pct_difs, cohens3) %>% 
  relocate(cohensd,cohensd2, effsize )

# still have to try to get cohen's d using sd_pool (mean diff bt group / pooled sd)
```

```{r}
#cohen's d calculation code reasoning
## 
 # find % visits to each cue / bat = visits to cue/ total visits in trial
 # find avg % visits / cue/ trial type/ species
#  find difference in average % visits
# also, calculate pooled sd (to calculate cohen's d that way)
# also just calculate cohen's d using the full data
 
 
# ### cohen's d calculation broken down: #####
# #from https://stats.stackexchange.com/questions/151781/cohens-d-calculation-in-r?rq=1
# lx <- n1- 1 #x
# ly <- n2- 1 #x
# md  <- abs(m1-m2)    #    ## mean difference (numerator)
# csd <- lx * s1^2 + ly * s2^2
# csd <- csd/(lx + ly)
# csd <- sqrt(csd)                     ## common sd computation
# 
# cd  <- md/csd                        ## cohen's d
# cd
# 
# #cohen's d calculation in the above equation
# lx <- (n_AJ - 1)
# ly <- (n_L-1)
# md <- (abs(diff))
# csd <- ((n_AJ - 1) *sd_AJ^2 + (n_L-1) * sd_L^2)
# csd <- ((n_AJ - 1) *sd_AJ^2 + (n_L-1) * sd_L^2) / ((n_AJ - 1) + (n_L-1))
# csd <- (sqrt(((n_AJ - 1) *sd_AJ^2 + (n_L-1) * sd_L^2) / ((n_AJ - 1) + (n_L-1))))
# cd <- (abs(diff)) / (sqrt(((n_AJ - 1) *sd_AJ^2 + (n_L-1) * sd_L^2) / ((n_AJ - 1) + (n_L-1))))


###
```






